[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['npm ci --only=production']

[phases.build]
cmds = [
  'npm install --save-dev vite @vitejs/plugin-vue',
  'npm run build'
]

[start]
cmd = './start.sh'