[phases.setup]
nixPkgs = ['nodejs-18_x']
aptPkgs = ['nodejs', 'npm']

[phases.install]
cmds = ['npm ci --only=production', 'npm install -g serve']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'serve -s dist -l $PORT'