#!/bin/bash

echo "🚀 Portfolio Site Deployment Script"
echo "=================================="

echo ""
echo "📋 STEP 1: Railway Backend Deployment"
echo "======================================"
echo ""
echo "1. Go to: https://railway.app"
echo "2. Login with GitHub"
echo "3. Click 'New Project'"
echo "4. Select 'Deploy from GitHub repo'"
echo "5. Choose: officerebel/Small_architecture_site"
echo ""
echo "🔧 Environment Variables to set in Railway:"
echo "DEBUG=False"
echo "SECRET_KEY=$(openssl rand -base64 32)"
echo "USE_SQLITE=False"
echo "ALLOWED_HOSTS=*.up.railway.app,localhost"
echo "WAGTAILADMIN_BASE_URL=https://your-app-name.up.railway.app"
echo ""
echo "📦 Add PostgreSQL Database:"
echo "- Click '+ New' → 'Database' → 'PostgreSQL'"
echo ""

echo "📋 STEP 2: Vercel Frontend Deployment"
echo "====================================="
echo ""
echo "1. Go to: https://vercel.com"
echo "2. Login with GitHub"
echo "3. Click 'New Project'"
echo "4. Import: officerebel/Small_architecture_site"
echo "5. Set Root Directory: frontend"
echo "6. Set Build Command: npm run build"
echo "7. Set Output Directory: dist"
echo ""
echo "🔧 Environment Variable to set in Vercel:"
echo "VITE_API_URL=https://your-railway-app.up.railway.app/api/"
echo ""

echo "📋 STEP 3: Final Setup"
echo "====================="
echo ""
echo "After Railway deployment, run in Railway terminal:"
echo "python manage.py setup_initial_data"
echo ""
echo "🎉 Your live URLs will be:"
echo "- Frontend: https://your-app.vercel.app"
echo "- Backend Admin: https://your-railway-app.up.railway.app/cms/"
echo "- API: https://your-railway-app.up.railway.app/api/"
echo ""
echo "🔑 Default login: admin / changeme123"
echo ""

read -p "Press Enter to open Railway deployment page..."
open "https://railway.app/new/template?template=https://github.com/officerebel/Small_architecture_site"

read -p "Press Enter to open Vercel deployment page..."
open "https://vercel.com/new/clone?repository-url=https://github.com/officerebel/Small_architecture_site"

echo "✅ Deployment pages opened in browser!"
echo "Follow the steps above to complete deployment."